#define flecs_monitor_STATIC
#ifndef FLECS_MONITOR_H
#define FLECS_MONITOR_H

/* This generated file contains includes for project dependencies */
/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef FLECS_MONITOR_BAKE_CONFIG_H
#define FLECS_MONITOR_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <flecs_meta.h>
#include <flecs_components_http.h>

/* Convenience macro for exporting symbols */
#ifndef flecs_monitor_STATIC
#if flecs_monitor_EXPORTS && (defined(_MSC_VER) || defined(__MINGW32__))
  #define FLECS_MONITOR_API __declspec(dllexport)
#elif flecs_monitor_EXPORTS
  #define FLECS_MONITOR_API __attribute__((__visibility__("default")))
#elif defined _MSC_VER
  #define FLECS_MONITOR_API __declspec(dllimport)
#else
  #define FLECS_MONITOR_API
#endif
#else
  #define FLECS_MONITOR_API
#endif

#endif


ECS_STRUCT(EcsMonitorServer, {
    int16_t port;
});

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlecsMonitor {
    ECS_DECLARE_COMPONENT(EcsMonitorServer);
} FlecsMonitor;

FLECS_MONITOR_API void FlecsMonitorImport(
    ecs_world_t *world);

#define FlecsMonitorImportHandles(handles) \
    ECS_IMPORT_COMPONENT(handles, EcsMonitorServer);

#ifdef __cplusplus
}
#endif

#endif
