function(link_system_libs target_name)
    if (WIN32)
        target_link_libraries(${target_name} winmm)
    elseif (APPLE)
        target_link_libraries(${target_name} pthread m dl)
    elseif (UNIX)
        target_link_libraries(${target_name} pthread m dl atomic)
    endif()
endfunction()
